name: Scheduled dbt Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
      SNOWFLAKE_PRIVATE_KEY_PATH: /home/runner/.dbt/keys/rsa_key.p8
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install "dbt-core==1.11.11" "dbt-snowflake==1.11.6"

      - name: Create dbt profile
        run: |
          mkdir -p /home/runner/.dbt
          cat > /home/runner/.dbt/profiles.yml <<EOF
          ecommerce_growth_analytics:
            target: prod
            outputs:
              prod:
                type: snowflake
                account: "${SNOWFLAKE_ACCOUNT}"
                user: "${SNOWFLAKE_USER}"
                private_key_path: "${SNOWFLAKE_PRIVATE_KEY_PATH}"
                private_key_passphrase: "${SNOWFLAKE_PRIVATE_KEY_PASSPHRASE}"
                role: "${SNOWFLAKE_ROLE}"
                database: "${SNOWFLAKE_DATABASE}"
                warehouse: "${SNOWFLAKE_WAREHOUSE}"
                schema: "${SNOWFLAKE_SCHEMA}"
                threads: 4
                client_session_keep_alive: false
          EOF

      - name: Write Snowflake private key
        run: |
          mkdir -p /home/runner/.dbt/keys
          cat > /home/runner/.dbt/keys/rsa_key.p8 <<EOF
          ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
          EOF
          chmod 600 /home/runner/.dbt/keys/rsa_key.p8

      - name: Show dbt files
        run: |
          echo "Current folder:"
          pwd
          echo "Project files:"
          ls -la
          echo ".dbt files:"
          ls -la /home/runner/.dbt
          echo "Profile preview:"
          sed -n '1,25p' /home/runner/.dbt/profiles.yml

      - name: Check dbt connection
        run: dbt debug

      - name: Build dbt project
        run: dbt build

      - name: Generate dbt docs
        run: dbt docs generate